name: Build docker container 

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 0,3"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: docker/build-push-action@v1
              with:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                repository: docker.pkg.github.com/js947/performance-test
                tag_with_ref: true
                tag_with_sha: true