name: Test spack build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get spack
        uses: actions/checkout@v2
        with:
          path: ./spack
          repository: spack/spack
          ref: develop

      - name: Install dependencies
        run: |
          source spack/share/spack/setup-env.sh
          spack install fenics-dolfinx

      - name: Build performance-test
        run: |
          source spack/share/spack/setup-env.sh
          spack load fenics-dolfinx
          mkdir build
          cd build
          cmake ../src
          make

      - name: Run Poisson test (BoomerAMG, serial)
        run: |
          source spack/share/spack/setup-env.sh
          spack load fenics-dolfinx
          build/dolfinx-scaling-test \
          --problem_type poisson \
          --scaling_type weak \
          --ndofs 50000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type hypre \
          -pc_hypre_type boomeramg \
          -pc_hypre_boomeramg_strong_threshold 0.5

      - name: Run elasticity test (GAMG, serial)
        run: |
          source spack/share/spack/setup-env.sh
          spack load fenics-dolfinx
          build/dolfinx-scaling-test \
          --problem_type elasticity \
          --scaling_type weak \
          --ndofs 100000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg \
          -pc_gamg_coarse_eq_limit 1000 \
          -mg_levels_ksp_type chebyshev \
          -mg_levels_pc_type jacobi \
          -mg_levels_esteig_ksp_type cg \
          -matptap_via scalable
